[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.31
    adafruit/Adafruit MPU6050 @ ^2.2.4
    adafruit/Adafruit MCP9808 Library @ ^2.0.0
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    mathieucarbou/ESPAsyncWebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson
    
build_flags =
    -D USER_SETUP_LOADED=1
    -D CORE_DEBUG_LEVEL=0
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=2
    -D TFT_RST=4
    -D TOUCH_CS=15
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=27000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D I2C_SPEED=400000